#!/bin/bash

#COLORED OUTPUT
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly RESET='\033[0m'

#IS AN ARGUMENT GIVEN?
if [ "${#}" -ne 1 ]; then
        printf "${RED}Missing file${RESET}\nUsage: %s <FILE>\n" "$(basename "${0}")"
        exit 1
fi

#----------------------------------------------------------------------

#ARGUMENT AS VARIABLE
readonly FILE="${1}"

#DOES FILE EXIST?
if [ ! -f "${FILE}" ]; then
	printf "${RED}File doesn't exist${RESET}\n"
	exit 1
fi

#OTHER VARIABLES
readonly FILENAME="$(basename "${FILE}")"
readonly PATH_WORKSPACE="$([ "${EUID}" -ne 0 ] && echo "${HOME}/Desktop/Git/" \
|| echo "${HOME}/Git/")"
readonly PATH_PROJECT="${PATH_WORKSPACE}${FILENAME}/"

#DOES WORKSPACE EXIST?
if [ ! -d "${PATH_WORKSPACE}" ]; then
	if mkdir -p "${PATH_WORKSPACE}"; then
		printf "[+] ${GREEN}Workspace created:\t%s${RESET}\n" "${PATH_WORKSPACE}"
	else
		printf "[-] ${RED}Something went wrong creating workspace${RESET}\n"
		exit 1
	fi
else
	#DOES PROJECT ALREADY EXIST?
	if [ -d "${PATH_PROJECT}" ]; then
	        printf "${RED}Project already exist in workspace${RESET}\n"
	        exit 1
	fi
fi

#----------------------------------------------------------------------

#CREATE PROJECT IN WORKSPACE
if mkdir "${PATH_PROJECT}"; then
	printf "[+] ${GREEN}Project created:\t%s${RESET}\n" "${PATH_PROJECT}"
else
	printf "[-] ${RED}Something went wrong creating project${RESET}\n"
	exit 1
fi

#MOVE FILE INTO PROJECT FOLDER
if mv "${FILE}" "${PATH_PROJECT}"; then
        printf "[+] ${GREEN}File moved:\t\t%s${RESET}\n" "${PATH_PROJECT}${FILENAME}"
else
	printf "[-] ${RED}Something went wrong moving file${RESET}\n"
	exit 1
fi

#INITIALIZE GIT IN PROJECT FOLDER
if cd "${PATH_PROJECT}" || exit 1; output="$(git init | cut -f 6- -d ' ')"; echo "# ${FILENAME}" > README.md; then
	printf "[+] ${GREEN}Git initialized:\t%s${RESET}\n" "$output"
else
	printf "[-] ${RED}Something went wrong initializing Git${RESET}\n"
	exit 1
fi

printf "For symlink: '%s'\n" "sudo ln -s ${PATH_PROJECT}${FILENAME} /usr/local/bin/${FILENAME}"
