#!/bin/bash

# This script will create a project workspace for you.
# If you started making a script/file, use it as input for this program.
# It will:
# 	1) Create a folder (/Desktop/Git/project_name) with the name of the script/file
# 	2) Move the file into that folder
# 	3) Initialize a Git rep in that folder
# ----------------------------------------------------------------------

#COLORED OUTPUT
declare -r RED='\033[0;31m'
declare -r GREEN='\033[0;32m'
declare -r RESET='\033[0m'

#IS AN ARGUMENT (a file) GIVEN?
if [ "$#" -ne 1 ]; then
        printf "${RED}Missing file.${RESET} Usage: %s <FILE>\n" "$(basename "$0")"
        exit 1
fi

#----------------------------------------------------------------------

#ARGUMENT AS VARIABLE
declare -r FILE="$1"

#DOES FILE EXIST?
if [ ! -f "${FILE}" ]; then
	printf "${RED}File doesn't exist${RESET}\n"
	exit 1
fi

#OTHER VARIABLES
FILENAME="$(basename "${FILE}")"; declare -r FILENAME
PATH_WORKSPACE="$([ "${EUID}" -ne 0 ] && echo "${HOME}/Desktop/Git/" \
|| echo "${HOME}/Git/")"; declare -r PATH_WORKSPACE
declare -r PATH_PROJECT="${PATH_WORKSPACE}${FILENAME}/"

#DOES WORKSPACE EXIST?
if [ ! -d "${PATH_WORKSPACE}" ]; then
	if mkdir -p "${PATH_WORKSPACE}"; then
		printf "[+] ${GREEN}Workspace created:\t%s${RESET}\n" "${PATH_WORKSPACE}"
	else
		printf "[-] ${RED}Something went wrong creating workspace${RESET}\n"
		exit 1
	fi
else
	#DOES PROJECT ALREADY EXIST?
	if [ -d "${PATH_PROJECT}" ]; then
	        printf "${RED}Project already exist in workspace${RESET}\n"
	        exit 1
	fi
fi

#----------------------------------------------------------------------

#CREATE PROJECT IN WORKSPACE
if mkdir "${PATH_PROJECT}"; then
	printf "[+] ${GREEN}Project created:\t%s${RESET}\n" "${PATH_PROJECT}"
else
	printf "[-] ${RED}Something went wrong creating project${RESET}\n"
	exit 1
fi

#MOVE FILE INTO PROJECT FOLDER
if mv "${FILE}" "${PATH_PROJECT}"; then
        printf "[+] ${GREEN}File moved:\t\t%s${RESET}\n" "${PATH_PROJECT}${FILENAME}"
else
	printf "[-] ${RED}Something went wrong moving script${RESET}\n"
	exit 1
fi

#INITIALIZE GIT IN PROJECT FOLDER
if cd "${PATH_PROJECT}" || exit 1; output="$(git init | cut -f 6- -d ' ')"; then
	printf "[+] ${GREEN}Git initialized:\t%s${RESET}\n" "$output"
else
	printf "[-] ${RED}Something went wrong initializing Git${RESET}\n"
	exit 1
fi
